

services:
  app:
    container_name: golang-crud-clean-arch-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - postgres  # ⬅️ Tambah dependensi ke PostgreSQL
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: golang-cleanarch-postgres
    environment:
      POSTGRES_DB: gotrial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kakashik1
    ports:
       - "5435:5432"
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: golang-cleanarch-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: golang-cleanarch-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  postgres_data:
